### ISSUE TITLE
SQL Error: 0, SQLState: 22003

### ISSUE THREAD

**Issue by XiaoShenLong** [keedio/flume-ng-sql-source#70]
(PollableSourceRunner-SQLSource-s1) [ERROR - org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions(SqlExceptionHelper.java:146)] '3.987778894E9' in column '2' is outside valid range for the datatype INTEGER.

**Comment by lazaromedina** [comment]
Hi, 
for the information you provide, my best guess is that your column's datatype is not what you think it is. If your are completely sure that your datatype in column 2 is BIGINT instead of INTEGER, seems to be a problem in the database side or may be the jdbc driver for you database is not handling properly BIGINT type. 
The problem seems to be reproducible if creating table and inserting data. Flume-sql-source reads data so the message you are providing is a bit weird.
Try updating jdbc driver.
Please reopen if you can provide more information that connects the exception with Flume-sql-source.
best
